`timescale 1ns / 1ps
// ============================================================================
// mips_pipeline_full.v
// Hazard-Resilient 5-Stage Pipelined MIPS-32 Processor -- combined single-file
// build. Generated by concatenating the individual source modules from the
// original Vivado project (MIPS_attempt10) in dependency order:
//
//   alu.v
//   alu_control.v
//   control_unit.v
//   data_memory.v
//   forwarding_unit.v
//   hazard_detection_unit.v
//   instruction_memory.v
//   register_file.v
//   sign_extend.v
//   mips_pipeline.v   (top-level module: mips_pipeline)
//
// Note: This file intentionally omits the testbench (tb_mips_pipeline.v) so
// it can be used as a pure synthesizable design source. Simulate against the
// original testbench file separately.
// ============================================================================


// ============================================================================
// Source: alu.v
// ============================================================================
// ============================================================================
// alu.v
// 32-bit ALU. The 4-bit alu_ctrl selects the operation; `zero` is asserted
// when the result is 0 (used by beq/bne to decide the branch in EX).
// ============================================================================
module alu (
    input      [31:0] a,
    input      [31:0] b,
    input      [3:0]  alu_ctrl,
    output reg [31:0] result,
    output            zero
);
    // ALU operation encodings (produced by alu_control.v)
    localparam AND = 4'b0000,
               OR  = 4'b0001,
               ADD = 4'b0010,
               SUB = 4'b0110,
               SLT = 4'b0111;

    always @(*) begin
        case (alu_ctrl)
            AND: result = a & b;
            OR:  result = a | b;
            ADD: result = a + b;
            SUB: result = a - b;
            SLT: result = ($signed(a) < $signed(b)) ? 32'd1 : 32'd0;
            default: result = 32'd0;
        endcase
    end

    assign zero = (result == 32'd0);
endmodule

// ============================================================================
// Source: alu_control.v
// ============================================================================
// ============================================================================
// alu_control.v
// Second-level ("local") control. Combines the 2-bit ALUOp from the main
// control unit with the R-type funct field to pick the ALU operation.
//
//   ALUOp = 00  -> ADD   (lw / sw / addi : address or immediate add)
//   ALUOp = 01  -> SUB   (beq / bne     : subtract, test zero)
//   ALUOp = 10  -> look at funct         (R-type)
// ============================================================================
module alu_control (
    input      [1:0] alu_op,
    input      [5:0] funct,
    output reg [3:0] alu_ctrl
);
    localparam AND = 4'b0000,
               OR  = 4'b0001,
               ADD = 4'b0010,
               SUB = 4'b0110,
               SLT = 4'b0111;

    // R-type funct codes
    localparam F_ADD = 6'b100000,
               F_SUB = 6'b100010,
               F_AND = 6'b100100,
               F_OR  = 6'b100101,
               F_SLT = 6'b101010;

    always @(*) begin
        case (alu_op)
            2'b00: alu_ctrl = ADD;      // lw/sw/addi
            2'b01: alu_ctrl = SUB;      // beq/bne
            2'b10: begin                // R-type: decode funct
                case (funct)
                    F_ADD: alu_ctrl = ADD;
                    F_SUB: alu_ctrl = SUB;
                    F_AND: alu_ctrl = AND;
                    F_OR:  alu_ctrl = OR;
                    F_SLT: alu_ctrl = SLT;
                    default: alu_ctrl = ADD;
                endcase
            end
            default: alu_ctrl = ADD;
        endcase
    end
endmodule

// ============================================================================
// Source: control_unit.v
// ============================================================================
// ============================================================================
// control_unit.v
// Main control. Decodes the 6-bit opcode into the datapath control signals.
// Operates in the ID stage. The bundle is latched into ID/EX and travels down
// the pipe with the instruction (a "bubble" = all of these forced to 0).
//
// Supported opcodes:
//   R-type 000000 : add sub and or slt   (funct decides in alu_control)
//   addi   001000
//   lw     100011
//   sw     101011
//   beq    000100
//   bne    000101
//   j      000010
// ============================================================================
module control_unit (
    input      [5:0] opcode,
    output reg       reg_dst,     // 1: write rd (R-type); 0: write rt
    output reg       alu_src,     // 1: 2nd ALU operand = sign-ext imm
    output reg       mem_to_reg,  // 1: write-back value from data memory
    output reg       reg_write,   // 1: instruction writes a register
    output reg       mem_read,    // 1: lw
    output reg       mem_write,   // 1: sw
    output reg       branch,      // 1: beq/bne
    output reg       bne,         // 1: bne (invert the equal test)
    output reg       jump,        // 1: j
    output reg [1:0] alu_op
);
    localparam R_TYPE = 6'b000000,
               ADDI   = 6'b001000,
               LW     = 6'b100011,
               SW     = 6'b101011,
               BEQ    = 6'b000100,
               BNE    = 6'b000101,
               J      = 6'b000010;

    always @(*) begin
        // Safe defaults = NOP (writes nothing, no memory access, no control flow)
        reg_dst    = 1'b0;
        alu_src    = 1'b0;
        mem_to_reg = 1'b0;
        reg_write  = 1'b0;
        mem_read   = 1'b0;
        mem_write  = 1'b0;
        branch     = 1'b0;
        bne        = 1'b0;
        jump       = 1'b0;
        alu_op     = 2'b00;

        case (opcode)
            R_TYPE: begin
                reg_dst   = 1'b1;
                reg_write = 1'b1;
                alu_op    = 2'b10;
            end
            ADDI: begin
                alu_src   = 1'b1;
                reg_write = 1'b1;
                alu_op    = 2'b00;
            end
            LW: begin
                alu_src    = 1'b1;
                mem_to_reg = 1'b1;
                reg_write  = 1'b1;
                mem_read   = 1'b1;
                alu_op     = 2'b00;
            end
            SW: begin
                alu_src   = 1'b1;
                mem_write = 1'b1;
                alu_op    = 2'b00;
            end
            BEQ: begin
                branch = 1'b1;
                alu_op = 2'b01;
            end
            BNE: begin
                branch = 1'b1;
                bne    = 1'b1;
                alu_op = 2'b01;
            end
            J: begin
                jump = 1'b1;
            end
            default: ; // keep NOP defaults
        endcase
    end
endmodule

// ============================================================================
// Source: data_memory.v
// ============================================================================
// ============================================================================
// data_memory.v
// Harvard-style DATA memory (separate from instruction memory).
// Word-addressed internally; `addr` is a byte address (the ALU result).
// Read is combinational (lw in the MEM stage); write is clocked (sw).
// ============================================================================
module data_memory #(
    parameter WORDS = 256
)(
    input             clk,
    input             mem_read,
    input             mem_write,
    input      [31:0] addr,        // byte address (ALU result)
    input      [31:0] write_data,  // store data (rt)
    output     [31:0] read_data
);
    reg [31:0] mem [0:WORDS-1];
    integer i;

    initial for (i = 0; i < WORDS; i = i + 1) mem[i] = 32'h0000_0000;

    // Combinational read
    assign read_data = (mem_read) ? mem[addr[31:2]] : 32'h0000_0000;

    // Clocked write
    always @(posedge clk)
        if (mem_write)
            mem[addr[31:2]] <= write_data;
endmodule

// ============================================================================
// Source: forwarding_unit.v
// ============================================================================
// ============================================================================
// forwarding_unit.v
// Removes RAW data hazards WITHOUT stalling by steering already-computed
// results straight into the ALU inputs in the EX stage.
//
// Two forwarding paths (this is what the resume calls EX-EX and MEM-EX):
//   forward = 10  -> take EX/MEM.alu_result  (producer is 1 instr ahead, in MEM)
//   forward = 01  -> take MEM/WB.write_data  (producer is 2 instr ahead, in WB)
//   forward = 00  -> use the value read from the register file (no hazard)
//
// EX/MEM is checked first so the MOST RECENT producer wins when a register is
// written by two instructions in flight. $0 is never forwarded.
// ============================================================================
module forwarding_unit (
    input      [4:0] id_ex_rs,
    input      [4:0] id_ex_rt,
    input      [4:0] ex_mem_rd,      // destination reg in MEM stage
    input            ex_mem_regwrite,
    input      [4:0] mem_wb_rd,      // destination reg in WB stage
    input            mem_wb_regwrite,
    output reg [1:0] forward_a,      // control for ALU input A (rs)
    output reg [1:0] forward_b       // control for ALU input B (rt)
);
    always @(*) begin
        // ---- operand A (rs) ----
        if (ex_mem_regwrite && (ex_mem_rd != 5'd0) && (ex_mem_rd == id_ex_rs))
            forward_a = 2'b10;                                   // EX-EX
        else if (mem_wb_regwrite && (mem_wb_rd != 5'd0) && (mem_wb_rd == id_ex_rs))
            forward_a = 2'b01;                                   // MEM-EX
        else
            forward_a = 2'b00;

        // ---- operand B (rt) ----
        if (ex_mem_regwrite && (ex_mem_rd != 5'd0) && (ex_mem_rd == id_ex_rt))
            forward_b = 2'b10;                                   // EX-EX
        else if (mem_wb_regwrite && (mem_wb_rd != 5'd0) && (mem_wb_rd == id_ex_rt))
            forward_b = 2'b01;                                   // MEM-EX
        else
            forward_b = 2'b00;
    end
endmodule

// ============================================================================
// Source: hazard_detection_unit.v
// ============================================================================
// ============================================================================
// hazard_detection_unit.v   ("stall controller")
// The one hazard forwarding CANNOT fix: LOAD-USE.
// A lw produces its data only at the end of MEM, but the very next instruction
// needs it at the start of its EX. So we insert exactly ONE bubble; after that,
// the MEM-EX forwarding path delivers the loaded value.
//
// Detection (done in ID, looking at the instruction currently in ID/EX):
//   stall  <=  ID/EX.MemRead  AND
//              ( ID/EX.rt == IF/ID.rs  OR  ID/EX.rt == IF/ID.rt )
//
// On stall:  freeze the PC and the IF/ID register (re-fetch / re-decode the
//            same two instructions next cycle) and push a bubble into ID/EX.
// ============================================================================
module hazard_detection_unit (
    input            id_ex_mem_read,
    input      [4:0] id_ex_rt,
    input      [4:0] if_id_rs,
    input      [4:0] if_id_rt,
    output           stall          // 1 => insert one bubble this cycle
);
    assign stall = id_ex_mem_read &&
                   ((id_ex_rt == if_id_rs) || (id_ex_rt == if_id_rt));
endmodule

// ============================================================================
// Source: instruction_memory.v
// ============================================================================
// ============================================================================
// instruction_memory.v
// Harvard-style INSTRUCTION memory (separate from data memory).
// Word-addressed internally; the PC is a byte address so we index with
// addr[?:2]. Combinational read (fetch happens within the IF stage).
// The program is loaded from a hex file via $readmemh.
// ============================================================================

// https://www.dsi.unive.it/~gasparetto/materials/MIPS_Instruction_Set.pdf

module instruction_memory #(
    parameter WORDS    = 256,                 // 256 instructions
    parameter PROGFILE = "program.hex"
)(
    input      [31:0] addr,        // byte address (from PC)
    output     [31:0] instr
);
    reg [31:0] mem [0:WORDS-1];
    integer i;

    initial begin
        for (i = 0; i < WORDS; i = i + 1) mem[i] = 32'h0000_0000; // NOP fill
        $readmemh(PROGFILE, mem);
    end

    assign instr = mem[addr[31:2]]; // divide byte address by 4
endmodule

// ============================================================================
// Source: register_file.v
// ============================================================================
// ============================================================================
// register_file.v
// 32 x 32-bit MIPS register file.
//   - Two combinational read ports (used in the ID stage).
//   - One write port, clocked on the NEGATIVE edge.
//
// Why negedge write?  A value written by an instruction in WB becomes visible
// to an instruction reading in ID during the SAME cycle. That resolves the
// "distance-3" data hazard (producer in WB, consumer in ID) with no extra
// forwarding path. Distances 1 and 2 are handled by the forwarding_unit.
//
//   - Register $0 is hardwired to 0; writes to it are ignored.
// ============================================================================
module register_file (
    input             clk,
    input             we,        // RegWrite, arriving from the WB stage
    input      [4:0]  ra1,       // read address 1 (rs)
    input      [4:0]  ra2,       // read address 2 (rt)
    input      [4:0]  wa,        // write address (rd or rt)
    input      [31:0] wd,        // write data
    output     [31:0] rd1,
    output     [31:0] rd2
);
    integer i;
    reg [31:0] regs [0:31];

    initial for (i = 0; i < 32; i = i + 1) regs[i] = 32'b0;

    // Combinational reads; $0 always reads as 0.
    assign rd1 = (ra1 == 5'd0) ? 32'b0 : regs[ra1];
    assign rd2 = (ra2 == 5'd0) ? 32'b0 : regs[ra2];

    // Write on the falling edge, never to $0.
    always @(negedge clk)
        if (we && (wa != 5'd0))
            regs[wa] <= wd;
endmodule

// ============================================================================
// Source: sign_extend.v
// ============================================================================
// ============================================================================
// sign_extend.v
// Sign-extends the 16-bit immediate/offset to 32 bits. MIPS offsets are
// 16-bit words sign-extended to 32 bits (matches the course note:
// "16-bit sign extended to 32-bit").
// ============================================================================
module sign_extend (
    input      [15:0] in,
    output     [31:0] out
);
    assign out = {{16{in[15]}}, in};
endmodule

// ============================================================================
// Source: mips_pipeline.v
// ============================================================================
// ============================================================================
// mips_pipeline.v   -- TOP LEVEL
// Hazard-resilient 5-stage pipelined MIPS32 processor.
//
//   Stages :  IF  ->  ID  ->  EX  ->  MEM  ->  WB
//   Pipe regs:   IF/ID    ID/EX    EX/MEM    MEM/WB
//
//   Data hazards  : forwarding_unit (EX-EX, MEM-EX) + negedge regfile write
//   Load-use      : hazard_detection_unit inserts 1 bubble, then forwards
//   Control hazard: beq/bne resolved in EX (2-cycle flush)
//                   j       resolved in ID (1-cycle flush)
//   Memories      : separate instruction & data memory (Harvard)
//
// This file also declares the four pipeline registers (as `reg`s updated in
// clocked always blocks) and instantiates every functional unit.
// ============================================================================
module mips_pipeline #(
    parameter PROGFILE = "program.hex"
)(
    input clk,
    input reset
);
    // =====================================================================
    // IF STAGE
    // =====================================================================
    reg  [31:0] pc;
    wire [31:0] pc_plus4 = pc + 32'd4;
    wire [31:0] instr;

    instruction_memory #(.PROGFILE(PROGFILE)) imem (
        .addr (pc),
        .instr(instr)
    );

    // ---- IF/ID pipeline register ----
    reg [31:0] ifid_instr;
    reg [31:0] ifid_pc4;

    // =====================================================================
    // ID STAGE
    // =====================================================================
    wire [5:0]  opcode = ifid_instr[31:26];
    wire [4:0]  rs     = ifid_instr[25:21];
    wire [4:0]  rt     = ifid_instr[20:16];
    wire [4:0]  rd     = ifid_instr[15:11];
    wire [5:0]  funct  = ifid_instr[5:0];
    wire [15:0] imm16  = ifid_instr[15:0];
    wire [25:0] jaddr  = ifid_instr[25:0];

    // main control
    wire       c_reg_dst, c_alu_src, c_mem_to_reg, c_reg_write;
    wire       c_mem_read, c_mem_write, c_branch, c_bne, c_jump;
    wire [1:0] c_alu_op;
    control_unit ctrl (
        .opcode(opcode),
        .reg_dst(c_reg_dst), .alu_src(c_alu_src), .mem_to_reg(c_mem_to_reg),
        .reg_write(c_reg_write), .mem_read(c_mem_read), .mem_write(c_mem_write),
        .branch(c_branch), .bne(c_bne), .jump(c_jump), .alu_op(c_alu_op)
    );

    // register file
    wire [31:0] rf_rd1, rf_rd2;
    // write-back signals (declared here, driven by WB stage below)
    wire        wb_reg_write;
    wire [4:0]  wb_write_reg;
    wire [31:0] wb_write_data;

    register_file rf (
        .clk(clk), .we(wb_reg_write),
        .ra1(rs), .ra2(rt), .wa(wb_write_reg), .wd(wb_write_data),
        .rd1(rf_rd1), .rd2(rf_rd2)
    );

    // sign extend
    wire [31:0] imm32;
    sign_extend se (.in(imm16), .out(imm32));

    // jump target: (PC+4)[31:28] : jaddr : 00
    wire [31:0] jump_target = {ifid_pc4[31:28], jaddr, 2'b00};

    // hazard detection (load-use)
    wire stall;
    hazard_detection_unit hdu (
        .id_ex_mem_read(idex_mem_read),
        .id_ex_rt      (idex_rt),
        .if_id_rs      (rs),
        .if_id_rt      (rt),
        .stall         (stall)
    );

    // ---- ID/EX pipeline register ----
    reg        idex_reg_dst, idex_alu_src, idex_mem_to_reg, idex_reg_write;
    reg        idex_mem_read, idex_mem_write, idex_branch, idex_bne;
    reg [1:0]  idex_alu_op;
    reg [31:0] idex_rd1, idex_rd2, idex_imm32, idex_pc4;
    reg [4:0]  idex_rs, idex_rt, idex_rd;
    reg [5:0]  idex_funct;

    // =====================================================================
    // EX STAGE
    // =====================================================================
    wire [3:0] alu_ctrl;
    alu_control aluc (.alu_op(idex_alu_op), .funct(idex_funct), .alu_ctrl(alu_ctrl));

    // forwarding
    wire [1:0] forward_a, forward_b;
    forwarding_unit fwd (
        .id_ex_rs(idex_rs), .id_ex_rt(idex_rt),
        .ex_mem_rd(exmem_write_reg), .ex_mem_regwrite(exmem_reg_write),
        .mem_wb_rd(memwb_write_reg), .mem_wb_regwrite(memwb_reg_write),
        .forward_a(forward_a), .forward_b(forward_b)
    );

    // 3:1 forwarding muxes (00 = regfile value, 10 = EX/MEM alu, 01 = WB data)
    reg [31:0] fwd_a_val, fwd_b_val;
    always @(*) begin
        case (forward_a)
            2'b10:   fwd_a_val = exmem_alu_result;
            2'b01:   fwd_a_val = wb_write_data;
            default: fwd_a_val = idex_rd1;
        endcase
        case (forward_b)
            2'b10:   fwd_b_val = exmem_alu_result;
            2'b01:   fwd_b_val = wb_write_data;
            default: fwd_b_val = idex_rd2;
        endcase
    end

    // ALU
    wire [31:0] alu_in_b = idex_alu_src ? idex_imm32 : fwd_b_val;
    wire [31:0] alu_result;
    wire        alu_zero;
    alu alu_u (.a(fwd_a_val), .b(alu_in_b), .alu_ctrl(alu_ctrl),
               .result(alu_result), .zero(alu_zero));

    // destination register (RegDst)
    // the destination register number selected in the Execute (EX) stage, which will receive the instruction's result in the Write-Back (WB) stage
    wire [4:0] ex_write_reg = idex_reg_dst ? idex_rd : idex_rt;

    // branch resolution (in EX)
    wire [31:0] branch_target = idex_pc4 + (idex_imm32 << 2);
    wire        branch_taken  = idex_branch & (idex_bne ? ~alu_zero : alu_zero);

    // ---- EX/MEM pipeline register ----
    reg        exmem_mem_read, exmem_mem_write, exmem_mem_to_reg, exmem_reg_write;
    reg [31:0] exmem_alu_result, exmem_store_data;
    reg [4:0]  exmem_write_reg;

    // =====================================================================
    // MEM STAGE
    // =====================================================================
    wire [31:0] mem_read_data;
    data_memory dmem (
        .clk(clk),
        .mem_read (exmem_mem_read),
        .mem_write(exmem_mem_write),
        .addr     (exmem_alu_result),
        .write_data(exmem_store_data),
        .read_data(mem_read_data)
    );

    // ---- MEM/WB pipeline register ----
    reg        memwb_mem_to_reg, memwb_reg_write;
    reg [31:0] memwb_read_data, memwb_alu_result;
    reg [4:0]  memwb_write_reg;

    // =====================================================================
    // WB STAGE
    // =====================================================================
    assign wb_write_data = memwb_mem_to_reg ? memwb_read_data : memwb_alu_result;
    assign wb_write_reg  = memwb_write_reg;
    assign wb_reg_write  = memwb_reg_write;

    // =====================================================================
    // SEQUENTIAL: PC + all pipeline registers, with stall & flush control
    // =====================================================================

    // ---- PC ----
    always @(posedge clk) begin
        if (reset)                pc <= 32'd0;
        else if (branch_taken)    pc <= branch_target;   // control hazard (EX)
        else if (c_jump)          pc <= jump_target;      // control hazard (ID)
        else if (stall)           pc <= pc;               // load-use freeze
        else                      pc <= pc_plus4;
    end

    // ---- IF/ID ----
    always @(posedge clk) begin
        if (reset || branch_taken || c_jump) begin
            ifid_instr <= 32'h0000_0000;                  // flush -> NOP
            ifid_pc4   <= 32'h0000_0000;
        end else if (stall) begin
            ifid_instr <= ifid_instr;                     // freeze (hold)
            ifid_pc4   <= ifid_pc4;
        end else begin
            ifid_instr <= instr;
            ifid_pc4   <= pc_plus4;
        end
    end

    // ---- ID/EX ----
    // Bubble on reset, branch flush, or load-use stall.
    task idex_bubble; begin
        idex_reg_dst    <= 1'b0; idex_alu_src  <= 1'b0; idex_mem_to_reg <= 1'b0;
        idex_reg_write  <= 1'b0; idex_mem_read <= 1'b0; idex_mem_write  <= 1'b0;
        idex_branch     <= 1'b0; idex_bne      <= 1'b0; idex_alu_op     <= 2'b00;
        idex_rd1 <= 32'b0; idex_rd2 <= 32'b0; idex_imm32 <= 32'b0; idex_pc4 <= 32'b0;
        idex_rs  <= 5'b0;  idex_rt  <= 5'b0;  idex_rd    <= 5'b0;  idex_funct <= 6'b0;
    end endtask

    always @(posedge clk) begin
        if (reset || branch_taken || stall) begin
            idex_bubble;
        end else begin
            idex_reg_dst    <= c_reg_dst;
            idex_alu_src    <= c_alu_src;
            idex_mem_to_reg <= c_mem_to_reg;
            idex_reg_write  <= c_reg_write;
            idex_mem_read   <= c_mem_read;
            idex_mem_write  <= c_mem_write;
            idex_branch     <= c_branch;
            idex_bne        <= c_bne;
            idex_alu_op     <= c_alu_op;
            idex_rd1        <= rf_rd1;
            idex_rd2        <= rf_rd2;
            idex_imm32      <= imm32;
            idex_pc4        <= ifid_pc4;
            idex_rs         <= rs;
            idex_rt         <= rt;
            idex_rd         <= rd;
            idex_funct      <= funct;
        end
    end

    // ---- EX/MEM ----
    always @(posedge clk) begin
        if (reset) begin
            exmem_mem_read <= 0; exmem_mem_write <= 0;
            exmem_mem_to_reg <= 0; exmem_reg_write <= 0;
            exmem_alu_result <= 0; exmem_store_data <= 0; exmem_write_reg <= 0;
        end else begin
            exmem_mem_read   <= idex_mem_read;
            exmem_mem_write  <= idex_mem_write;
            exmem_mem_to_reg <= idex_mem_to_reg;
            exmem_reg_write  <= idex_reg_write;
            exmem_alu_result <= alu_result;
            exmem_store_data <= fwd_b_val;        // forwarded rt value (for sw)
            exmem_write_reg  <= ex_write_reg;
        end
    end

    // ---- MEM/WB ----
    always @(posedge clk) begin
        if (reset) begin
            memwb_mem_to_reg <= 0; memwb_reg_write <= 0;
            memwb_read_data <= 0; memwb_alu_result <= 0; memwb_write_reg <= 0;
        end else begin
            memwb_mem_to_reg <= exmem_mem_to_reg;
            memwb_reg_write  <= exmem_reg_write;
            memwb_read_data  <= mem_read_data;
            memwb_alu_result <= exmem_alu_result;
            memwb_write_reg  <= exmem_write_reg;
        end
    end
endmodule
